import "./Publications.css"
function Publications() {
    return (
        <div className="home">
            <div className="home-title">Recent Selected Publications Since 2020</div>
            <ul>
                <li><strong>X Liao*</strong>, J Yin, M Chen, Z Qin, Adaptive payload distribution in multiple images steganography based on image texture features. IEEE Transactions on Dependable and Secure Computing (<strong>TDSC</strong>), DOI: 10.1109/TDSC.2020.3004708, 2020. [<strong>CCF A</strong>] [<strong>ESI Highly Cited Paper</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/Adaptive_Payload_Distribution_in_Multiple_Images_Steganography_Based_on_Image_Texture_Features.pdf">pdf</a>]</li>
                <li><strong>X Liao*</strong>, K Li, X Zhu, K. J. R Liu, Robust detection of image operator chain with two-stream convolutional neural network. IEEE Journal of Selected Topics in Signal Processing (<strong>JSTSP</strong>), vol. 14, no. 5, pp. 955-968, 2020. [<strong>TOP Journal</strong>] [<strong>ESI Highly Cited Paper</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/Robust_Detection_of_Image_Operator_Chain_With_Two-Stream_Convolutional_Neural_Network.pdf">pdf</a>]</li>
                <li><strong>X Liao*</strong>, Y Yu, B Li, Z Li, Z Qin, A new payload partition strategy in color image steganography. IEEE Transactions on Circuits and Systems for Video Technology (<strong>TCSVT</strong>), vol. 30, no. 3, pp. 685-696, 2020. <strong>[ESI Highly Cited Paper]</strong> [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/A_New_Payload_Partition_Strategy_in_Color_Image_Steganography.pdf">pdf</a>]</li>
                <li>J Hu, <strong>X Liao*</strong>, J Liang, W Zhou, Z Qin, FInfer: Frame inference-based deepfake detection for high-visual-quality videos. Association for the Advancement of Artificial Intelligence (<strong>AAAI</strong>), 2022. [<strong>CCF A</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/AAAI-22-Finfer.pdf">pdf</a>]</li>
                <li>X Wu, <strong>X Liao*</strong>, B Ou, SepMark: Deep Separable Watermarking for Unified Source Tracing and Deepfake Detection. ACM International Conference on Multimedia (<strong>ACM MM</strong>), 2023. [<strong>CCF A</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/SepMark Deep Separable Watermarking for Unified Source Tracing and Deepfake Detection.pdf">pdf</a>]</li>
                <li>J Yang, <strong>X Liao*</strong>, Exploiting Fine-Grained DCT Representations for Hiding Image-Level Messages within JPEG Images. ACM International Conference on Multimedia (<strong>ACM MM</strong>), 2023. [<strong>CCF A</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/Exploiting Fine-Grained DCT Representations for Hiding Image-Level Messages within JPEG Images.pdf">pdf</a>]</li>
                <li>M Chen*, <strong>X Liao</strong>, M Wu, PulseEdit: Editing physiological signal in facial videos for privacy protection. IEEE Transactions on Information Forensics and Security (<strong>TIFS</strong>), DOI: 10.1109/TIFS.2022.3142993, 2022. [<strong>CCF A</strong>]</li>
                <li>J Hu, <strong>X Liao*</strong>, W Wang, Z Qin, Detecting compressed Deepfake video in social networks using frame-temporality two-stream convolutional network. IEEE Transactions on Circuits and Systems for Video Technology (<strong>TCSVT</strong>), DOI: 10.1109/TCSVT.2021.3074259, 2021. [<strong>ESI Highly Cited Paper</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/IEEE TCSVT-Detecting compressed Deepfake video in social networks using frame-temporality two-stream convolutional network.pdf">pdf</a>]</li>
                <li><strong>X Liao*</strong>, Y Wang, T Wang, J Hu, X Wu，FAMM: Facial Muscle Motions for Detecting Compressed Deepfake Videos over Social Networks. IEEE Transactions on Circuits and Systems for Video Technology (<strong>TCSVT</strong>), DOI：10.1109/TCSVT.2023.3278310, 2023. [<strong>SCI #1</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/IEEE TCSVT-FAMM Facial muscle motions for detecting compressed Deepfake videos over social networks.pdf">pdf</a>]</li>
                <li>J Chen, <strong>X Liao*</strong>, W Wang, Z Qian, Z Qin, Y Wang，SNIS: A Signal Noise Separation-based Network for Post-processed Image Forgery Detection. IEEE Transactions on Circuits and Systems for Video Technology (<strong>TCSVT</strong>), DOI：10.1109/TCSVT.2022.3204753, 2022. [<strong>SCI #1</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/IEEE TCSVT-SNIS A signal noise separation-based network for post-processed image forgery detection.pdf">pdf</a>]</li>
                <li>J Tan, <strong>X Liao*</strong>, J Liu, Y Cao, H Jiang, Channel attention image steganography with generative adversarial networks. IEEE Transactions on Network Science and Engineering (<strong>TNSE</strong>), DOI: 10.1109/TNSE.2021.3139671, 2021. [<strong>SCI #1</strong>] [<strong>ESI Highly Cited Paper</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/IEEE TNSE-Channel attention image steganography with generative adversarial networks.pdf">pdf</a>]</li>
                <li>Y Zhang, J Ni, W Su, <strong>X Liao</strong>, A Novel Deep Video Watermarking Framework with Enhanced Robustness to H.264/AVC Compression. ACM International Conference on Multimedia (<strong>ACM MM</strong>), 2023. [<strong>CCF A</strong>]</li>
                <li>Z Chen, H Liu*, L Zhang, <strong>X Liao</strong>, Multi-dimensional attention with similarity constraint for weakly-supervised temporal action localization, IEEE Transactions on Multimedia (<strong>TMM</strong>), DOI: 10.1109/TMM.2022.3174344, 2022. [<strong>SCI #1</strong>]</li>
                <li>Y Li, J You, J Zhou*, W Wang, <strong>X Liao</strong>, X Li, Image operation chain detection with machine translation framework. IEEE Transactions on Multimedia (<strong>TMM</strong>), DOI: 10.1109/TMM.2022.3215000, 2022. [<strong>SCI #1</strong>]</li>
                <li>F Li, Y Chen, H Liu, Z Zhao, Y Yao, <strong>X Liao</strong>, Vocoder detection of spoofing speech based on GAN fingerprints and domain generalization. ACM Transactions on Multimedia Computing, Communications, and Applications(<strong>TOMM</strong>), DOI: 10.1145/3630751, 2023.</li>
                <li>Y Tian, <strong>X Liao</strong>, L Dong, Y Xu, H Jiang, Amount-based covert communication over blockchain. IEEE Transactions on Network and Service Management(<strong>TNSM</strong>), DOI: 10.1109/TNSM.2024.3358013, 2024.</li>
                <li>J Chen, G Yang, S Wang, D Wang, <strong>X Liao</strong>, Image dehazing assessment: A real-world dataset and a haze density-aware criteria, IEEE Transactions on Multimedia(<strong>TMM</strong>), DOI: 10.1109/TMM.2023.3345141, 2023. [<strong>SCI #1</strong>]</li>
                <li>Y Sun*, K Yu, A K Bashir, <strong>X Liao</strong>, Bl-IEA: A bit-level image encryption algorithm for cognitive services in intelligent transportation systems. IEEE Transactions on Intelligent Transportation Systems (<strong>TITS</strong>), DOI: 10.1109/TITS.2021.3129598, 2021. [<strong>SCI #1</strong>]</li>
                <li>Y Liu<em>, C Wang, J Wang</em>, B Liao, <strong>X Liao</strong>, Generative steganography via live comments on streaming video frames. IEEE Transactions on Computational Social Systems (<strong>TCSS</strong>), DOI: 10.1109/TCSS.2024.3352979, 2024.</li>
                <li><strong>X Liao*</strong>, Z Huang, L Peng, T Qiao, First step towards parameters estimation of image operator chain. Information Science (<strong>INS</strong>), vol. 575, pp. 231-247, 2021. [<strong>SCI #1</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/First step towards parameters estimation of image operator chain.pdf">pdf</a>]</li>
                <li>J Chen, <strong>X Liao*</strong>, W Wang, Z Qin, Identification of image global processing operator chain based on feature decoupling. Information Science (<strong>INS</strong>), DOI: 10.1016/j.ins.2023.118961, 2023. [<strong>SCI #1</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/INS-Identification of image global processing operator chain based on feature decoupling.pdf">pdf</a>]</li>
                <li>Y Yang*, B Wang, Y Yang, Y Zhou, W Shi, <strong>X Liao</strong>, Visually meaningful image encryption based on universal embedding model. Information Science (<strong>INS</strong>), vol. 562, pp. 304-324, 2021. [<strong>SCI #1</strong>]</li>
                <li>Y Yang*, B Wang, S Pei, Y Zho, W Shi, <strong>X Liao</strong>, Using M-ary decomposition and virtual bits for visually meaningful image encryption. Information Science (<strong>INS</strong>), vol. 580, pp. 174-201, 2021. [<strong>SCI #1</strong>]</li>
                <li><strong>X Liao*</strong>, Z Huang, A framework for parameters estimation of image operator chain. IEEE International Conference on Acoustics, Speech and Signal Processing (<strong>ICASSP</strong>), Barcelona, Spain. May 4-8, 2020: 2787-2791. [<strong>CCF B</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/A_Framework_for_Parameters_Estimation_of_Image_Operator_Chain.pdf">pdf</a>]</li>
                <li>J Chen, <strong>X Liao*</strong>, W Wang, Z Qin, A features decoupling method for multiple manipulations identification in image operation chains. IEEE International Conference on Acoustics, Speech and Signal Processing (<strong>ICASSP</strong>), Toronto, ON, Canada. June 6-11, 2021: 2505-2509. [<strong>CCF B</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/A_Features_Decoupling_Method_for_Multiple_Manipulations_Identification_in_Image_Operation_Chains.pdf">pdf</a>]</li>
                <li>Y Sun, <strong>X Liao*</strong>, J Liu, An efficient paper anti-counterfeiting method based on microstructure orientation estimation. IEEE International Conference on Acoustics, Speech and Signal Processing (<strong>ICASSP</strong>), Toronto, ON, Canada. June 6-11, 2021: 2525-2529. [<strong>CCF B</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/An_Efficient_Paper_Anti-Counterfeiting_Method_Based_on_Microstructure_Orientation_Estimation.pdf">pdf</a>]</li>
                <li><strong>X Liao*</strong>, Z Tang, Y Cao, Steganographic distortion function learning method for spatial color image based on generative adversarial network. Journal of Software, vol. 33, no. 9, pp. 3470-3484, 2022. (in Chinese) [<strong>CCF A</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/tangziqiang.pdf">pdf</a>]</li>
                <li>J Shen, <strong>X Liao*</strong>, Z Qin, X Liu, Spatial steganalysis of low embedding rate based on convolutional neural network. Journal of Software, vol. 32, no. 9, pp. 2901−2915, 2021. (in Chinese) [<strong>CCF A</strong>] [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/shenjun.pdf">pdf</a>]</li>
                <li><strong>X Liao*</strong>, J Peng, Y Cao, GIFMarking: The robust watermarking for animated GIF based deep learning. Journal of Visual Communication and Image Representation (<strong>JVCIR</strong>), vol. 79, 103244, 2021. [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/GIFMarking The robust watermarking for animated GIF based deep learning.pdf">pdf</a>]</li>
                <li><strong>X Liao</strong>, J Chen, J Chen*, Image source identification with known post-processed based on convolutional neural network. Signal Processing: Image Communication (<strong>SPIC</strong>), vol. 99, 116438, 2021. [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/Image source identification with known post-processed based on convolutional neural network.pdf">pdf</a>]</li>
                <li>J Chen, <strong>X Liao*</strong>, Z Qin, Identifying tampering operations in image operator chains based on decision fusion. Signal Processing: Image Communication (<strong>SPIC</strong>), vol. 95, 116287, 2021. [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/Identifying tampering operations in image operator chains based on decision fusion.pdf">pdf</a>]</li>
                <li>J Yang, <strong>X Liao*</strong>, ACGIS: Adversarial cover generator for image steganography with noise residuals features-preserving. Signal Processing: Image Communication (<strong>SPIC</strong>), vol. 113, 116927, 2023. [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/JYang.pdf">pdf</a>]</li>
                <li>J Yang, <strong>X Liao*</strong>, An embedding strategy on fusing multiple image features for data hiding in multiple images. Journal of Visual Communication and Image Representation (<strong>JVCIR</strong>), vol. 71, 102822, 2020. [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/An embedding strategy on fusing multiple image features for data hiding in multiple images.pdf">pdf</a>]</li>
                <li>L Peng, <strong>X Liao*</strong>, M Chen, Resampling parameter estimation via dual-filtering based convolutional neural network. Multimedia Systems (<strong>MS</strong>), vol. 27, pp. 363-370, 2021. [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/Resampling parameter estimation via dual-filtering based convolutional neural network.pdf">pdf</a>]</li>
                <li>S Gao, J Chen*, <strong>X Liao</strong>. Exploring feature coupling for multiple operations type and order detection. IEEE International Workshop on Multimedia Signal Processing (<strong>MMSP</strong>), 2022. [<a href="https://github.com/xin-liao/xin-liao.github.io/blob/main/resource/Exploring feature coupling for multiple operations type and order detection.pdf">pdf</a>]</li>
            </ul>
        </div>
    )
}

export default Publications;